[book]
title = "Verto Trading Post Book"
authors = ["Verto Authors"]
description = "Documentation to run a trading post on the Verto Protocol"
multilingual = false
src = "src"

[build]
build-dir = "build"

[output.html]
mathjax-support = true