name: ci

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Setup node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install yarn
        run: npm i --global yarn
      - name: Install dependencies
        run: yarn
      - name: Check fmt
        run: yarn check:fmt
      - name: Build
        run: yarn dist
