name: Ship

on:
  workflow_dispatch:

jobs:
  ship:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Setup Deno
        if: startsWith(matrix.os, 'ubuntu')
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.3.2

      - name: Get Version
        id: version
        run: echo "::set-output name=tag::$(node -p "require('./package.json').version")"

      - name: Generate Release Notes
        if: startsWith(matrix.os, 'ubuntu')
        run: deno run -A https://deno.land/x/prlog@0.3.1/prlog.ts useverto/trading-post -v ${{ steps.version.outputs.tag }} -t .github/release.t.md -o release.md --auth ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Notes
        uses: actions/upload-artifact@v2
        if: startsWith(matrix.os, 'ubuntu')
        with:
          name: notes
          path: release.md
          if-no-files-found: error

      - name: Install dependencies
        run: |
          npm i -g yarn
          yarn

      - name: Package executables
        run: yarn pkg

      - name: Zip linux release
        if: startsWith(matrix.os, 'ubuntu')
        run: zip -r verto-x64-linux.zip verto README.md LICENSE

      - name: Zip mac release
        if: startsWith(matrix.os, 'mac')
        run: zip -r verto-x64-macos.zip verto README.md LICENSE

      - name: Zip windows release
        if: startsWith(matrix.os, 'windows')
        run: Compress-Archive -CompressionLevel Optimal -Force -Path verto.exe, README.md, LICENSE -DestinationPath verto-x64-windows.zip

      - name: Upload release artifacts
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: |
            verto-x64-linux.zip
            verto-x64-macos.zip
            verto-x64-windows.zip

      - name: Download artifacts
        uses: actions/download-artifact@v2

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.version.outputs.tag }}
          name: ${{ steps.version.outputs.tag }}
          draft: true
          prerelease: false
          allowUpdates: true
          replacesArtifacts: true
          artifacts: "release/*"
          bodyFile: "notes/release.md"
          token: ${{ secrets.GITHUB_TOKEN }}
